debug: true
server:
  port: 8080
spring:
  # servlet配置
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  # mongodb配置
  data:
    mongodb:
      database: ps2
      uri: mongodb://localhost:27017

